### ISSUE TITLE
Mahalanobis distance for singular covariance data

### ISSUE THREAD

**Issue by ck37** [mlampros/KernelKnn#1]
Hi,

Great package, I really appreciate all of the expanded hyperparameter options for nearest neighbors. I'm looking to use this on wide datasets with singular covariance matrices, which don't support Mahalanobis distance by default due to the matrix inversion failure for arma::inv().

I've found that if arma::inv() is changed to pinv() (pseudoinverse) in distance_metrics.cpp that Mahalanobis distance seems to work fine. Here is a paper that includes it (via Stackoverflow): http://www.sciencedirect.com/science/article/pii/0146664X79900522

But I don't know if it would be preferable to try to use arma:inv(), but check for failure and only use arma::pinv() if necessary. My C++ is a little rusty.

Alternatively, perhaps penalized Mahalanobis distance would be a helpful distance metric:
http://stefansavev.com/blog/better-euclidean-distance-with-the-svd-penalized-mahalanobis-distance/

Thanks,
Chris

**Comment by mlampros** [comment]
Hello and I'm sorry for the late reply,

thanks for the interesting links, just give me some time to read them and I'll come back with either an update or an additional distance metric function.

**Comment by ck37** [comment]
No worries at all, no rush! Appreciate the investigation

**Comment by ck37** [comment]
Also I should say that we've added KernelKnn support to the SuperLearner ensembling package: https://github.com/ecpolley/SuperLearner/pull/62

**Comment by mlampros** [comment]
thanks a lot for both including KernelKnn to the SuperLearner package and for making me aware of the Moore-Penrose pseudo-inverse. I have updated the package with a try-catch function as you suggested. The arma::inv() function is used by default and in case that the covariance matrix is singular then the arma::pinv() will be called. Moreover in case of a singular covariance matrix the function outputs a warning.
I tested it using the ionosphere data (the second column has a single unique value).
Please test the new version of the package with your data set and let me know.

**Comment by ck37** [comment]
Thank you, yes it seems to work for my current dataset. I'll continue testing on others and will report back if anything looks strange.

**Comment by mlampros** [comment]
I'll close the issue for now.
