### ISSUE TITLE
[Feature request]: provide the order "p" of the "minkowski" method as a new argument

### ISSUE THREAD

**Issue by sbcalaff** [mlampros/KernelKnn#9]
R package "KernelKnn" version 1.1.4.

The method "`minkowski`" uses (by default) the parameter "`k`" as the order "`p`". Would be possible to incorporate "`p`" as a new argument in the function `KernelKnn::KernelKnn`?

**Comment by mlampros** [comment]
@sbcalaff the [minkowski parameter is set to 'k' by default ](https://github.com/mlampros/KernelKnn/blob/master/src/distance_metrics.cpp#L106) in the Rcpp code. I have to go through the Rcpp code to adjust the functions (and adding the parameter 'p'). Give me a few days

**Comment by mlampros** [comment]
a minimal example to verify the results for a different 'p' value,

```R
data(Boston, package = 'KernelKnn')

X = Boston[, -dim(Boston)[2]]
y = Boston[, dim(Boston)[2]]

k = 2

# without specifying the 'p' parameter (it defaults to 'k')
res_wo = KernelKnn::KernelKnn(data = X, y = y, k = k, method = 'minkowski', regression = T, threads = 1)
# by specifying the 'p' parameter
res_w = KernelKnn::KernelKnn(data = X, y = y, k = k, method = 'minkowski', regression = T, threads = 1, p = k)
# 'p' is set to 1
res_dif = KernelKnn::KernelKnn(data = X, y = y, k = k, method = 'minkowski', regression = T, threads = 1, p = 1)

is_identical = identical(res_wo, res_w)
is_identical
# TRUE

is_not_identical = identical(res_wo, res_dif)
is_not_identical
# FALSE

```

the same can be done with the *KernelKnnCV()* and *knn.index.dist()* functions. The [NEWS.md](https://github.com/mlampros/KernelKnn/blob/master/NEWS.md#kernelknn-115) file includes the details.

Currently CRAN is offline and will accept new submissions after the 5th of January 2023. Thus, you can install the latest version that includes the updates using,

```R
remotes::install_github('mlampros/KernelKnn')

``` 

Feel free to re-open this issue if the code does not work as expected
